name: Flutter Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

    

      # Step 3: Verify Flutter and Dart versions
      - name: Verify installation
        run: |
          flutter --version
          dart --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Run all tests
      - name: Run all tests
        run: flutter home_page_test.dart 
